name: CI for Flask Application

on:
  push:
    branches:
      - only_backend
  pull_request:
    branches:
      - only_backend

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --quiet --config /etc/mongo/mongodb.conf

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Set up environment variables for tests
        export CLIENT_ID=${{ secrets.CLIENT_ID }}
        export CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        export APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}
        export MONGO_URI="mongodb://localhost:27017/"

        # Run your tests here
        python -m unittest discover -s tests

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
